### ISSUE TITLE
Multiple condition on Time field does not work.

### ISSUE THREAD

**Issue by DimaMelnik** [scale-tone/linq2dynamodb#50] opened 2017-10-24 05:20 UTC
Executing query 
x.Time >= DateTime.Parse("2017-09-13T22:17:52.000Z") && x.Time <= DateTime.Parse("2017-09-14T02:17:52.000Z") seems like only second part of expression applies .

**Comment by scale-tone** [comment] 2017-10-24 06:27
Duplicate of https://github.com/scale-tone/linq2dynamodb/issues/45 and a known issue.

Technically, the bug is in AWSSDK (it should throw in such scenario). 

The workaround is to use a custom FilterExpression.

**Closed by scale-tone** 2017-10-24 06:27 UTC
