### ISSUE TITLE
Cache entry for batch get is always being "rebuilt", never returns the cached item

### ISSUE THREAD

**Issue by maynardflies** [scale-tone/linq2dynamodb#49] opened 2017-10-18 20:40 UTC
So I'm using the Redis cache client with Linq2DynamoDb, and at present I am only testing it against a single batch get call.  When the Data context is instantiated, I (via another datacontext) create a table and insert two items into it.  Then my service does a batch get for those two items that looks like "where Hash Key = <hkey> and sort key in <skey1>,<skey2>.

The first time this is run, it as expected hits Dynamo for the values.  However, on subsequent runs, the redis caching library always throws an exception saying the "index is being rebuilt".  Looking at the cache, there are two keys there that look like they were correctly converted to Base64 that have the two items i'm expecting to see, there is an ":indexes" which has metadata about the batch get, and another that has the "query" with the "IndexVersion" as Long.MinValue+1 (which from the code I can see is the initializing value/index rebuilding value).

However, it always stays like that and never actually gets the items from the cache, always deferring to DynamoDB.  I've been going through the code but I'm still not sure what the problem is.

I also note that the StringSet calls subsequently fail for setting the entity values, but of course it doesn't tell you why, it just returns false.

Flummoxed.  Happy to post code snippets if you tell me what's relevant, but the majority of it looks just like the wiki.

**Comment by maynardflies** [comment] 2017-10-18 21:11
I'm running on .NET Core 2.0 by the way.  All the Datacontext stuff seems to work fine, I'm only having issues with the Redis portion never being "built"

**Comment by scale-tone** [comment] 2017-10-19 09:17
Hi, I believe, this is a duplicate of https://github.com/scale-tone/linq2dynamodb/issues/46.
There seems to be some compatibility issue between Newtonsoft.Json (> 10.0.1, which comes with .Net Core 2.0) and Linq2DynamoDb.DataContext.Caching.Redis. 

Will try to look at this in more detail...

**Comment by scale-tone** [comment] 2017-10-24 16:23
Found the issue. 
[This line should be uncommented](https://github.com/scale-tone/linq2dynamodb/blob/master/Sources/Linq2DynamoDb.DataContext.Caching.Redis/GeneralUtils.cs#L25) not only for .Net, but also for StackExchange.Redis > 10.0.1 on .Net Standard.

Will submit an updated [Linq2DynamoDb.DataContext.Caching.Redis](https://www.nuget.org/packages/Linq2DynamoDb.DataContext.Caching.Redis/) package....

**Comment by scale-tone** [comment] 2017-10-24 17:26
Can I please ask you to validate that [this version](https://www.nuget.org/packages/Linq2DynamoDb.DataContext.Caching.Redis/2.2.1) resolves the problem?

**Comment by scale-tone** [comment] 2017-10-29 00:25
Fixed with https://www.nuget.org/packages/Linq2DynamoDb.DataContext.Caching.Redis/2.2.1.

**Closed by scale-tone** 2017-10-29 00:25 UTC
